# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-21 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants'),
        ),
    ]
