# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-15 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20180915_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
