# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-21 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20180921_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='profile',
            new_name='cover_photo',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants'),
        ),
    ]
