# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-21 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20180921_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='inserted_at',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
