# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-21 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20180922_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='inserted_at',
        ),
        migrations.AlterField(
            model_name='food',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
