# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20180918_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
