# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-07 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20181107_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='FoodLike',
        ),
    ]
