# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-21 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datascrap',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
